---

- package:
    name: software-properties-common

- command: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8

- apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://mirror2.hs-esslingen.de/mariadb/repo/10.4/ubuntu bionic main
    filename: mariadb
    state: present
    update_cache: yes

- package:
    name:
      - mariadb-server
      - mariadb-client
      - python3-mysqldb

- service:
    name: mariadb
    state: started
    enabled: yes