---

- name: create group
  group:
    name: theia-ide
    state: present
    system: yes

- name: create user
  user:
    comment: theia-ide
    name: theia-ide
    group: theia-ide
    home: /srv/theia-ide
    shell: /bin/bash
    create_home: yes
    system: yes
    password_lock: yes

- file:
    path: /srv/theia-ide/{{ item }}
    state: directory
    owner: theia-ide
    group: theia-ide
    mode: 0750
  with_items:
    - bin

- name: download nodejs
  get_url:
    url: '{{ nodejs.url }}'
    dest: /tmp/nodejs.tar.xz
  become: yes
  become_method: su
  become_user: theia-ide

- unarchive:
    src: /tmp/nodejs.tar.xz
    dest: /tmp
    remote_src: yes

- copy:
    src: /tmp/{{ nodejs.filename }}/{{ item }}
    dest: /srv/theia-ide/.nodejs
    owner: theia-ide
    group: theia-ide
    mode: 0750
    remote_src: yes
  with_items:
    - bin
    - include
    - lib
    - share

- lineinfile:
    path: /srv/theia-ide/.bashrc
    line: export PATH=$HOME/.nodejs/bin:$PATH
    state: present

- npm:
    name: yarn
    state: present
    global: yes
  become: yes
  become_user: theia-ide
  become_method: sudo