- name: copy binaries
  ansible.builtin.copy:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/kubernetes/server/bin/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
  become: true
