- name: create {{ work_dir | default(plabook_dir + '/tmp') }}
  ansible.builtin.file:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}"
    state: directory
  delegate_to: localhost
  run_once: true
