grafana:
  version: 9.0.2
  checksum: 50dd7927c1313e47a30f531d0e3f145297c485666865a97a6c936427dd8a55fd
  user: grafana
  group: grafana
  port: 3000
  bin_dir: /usr/local/bin
  config_dir: /etc/grafana
  data_dir: /var/lib/grafana
  log_dir: /var/log/grafana
