---
- hosts: localhost
  gather_facts: false

  environment:
    KUBECONFIG: "{{ ansible_env.PWD }}/.kube/config"

  tasks:
    - name: Ensure the myapp Namespace exists.
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: ansible
        state: absent
