---
- hosts: localhost
  gather_facts: false

  environment:
    KUBECONFIG: "{{ ansible_env.PWD }}/.kube/config"

  tasks:
    - name: Create Ansible namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: ansible
        state: absent
