- name: generate private key
  openssl_privatekey:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.key"
    type: RSA
    size: 2048
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate csr
  openssl_csr:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.csr"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.key"
    common_name: "system:kube-scheduler"
    organization_name: "system:kube-scheduler"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate crt
  openssl_certificate:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.crt"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.key"
    csr_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.csr"
    provider: ownca
    ownca_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    ownca_privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.key"
    mode: 0644
  delegate_to: localhost
  run_once: true

- include_tasks: ../../common/tasks/kubeconfig.yml
  vars:
    kubeconfig_dest: /etc/kubernetes/kube-scheduler.kubeconfig
    key_file: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.key"
    crt_file: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-scheduler.crt"
    ca_file: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    notified_handler: restart kube-scheduler
