- name: Generate certificate
  include_tasks: cert.yml

- name: Get binary
  include_tasks: ../../common/tasks/get-binary.yml
  vars:
    binary: kubelet
    version: "{{ kubelet.version }}"
    checksum: "{{ kubelet.checksum }}"

- name: Copy kubelet-config.yaml
  ansible.builtin.template:
    src: templates/kubelet-config.yaml
    dest: /etc/kubernetes/kubelet-config.yaml
    owner: "{{ kubernetes.user }}"
    group: "{{ kubernetes.group }}"
    mode: 0600
  become: true
  notify: Restart kubelet

- name: Copy kubelet.service
  ansible.builtin.template:
    src: templates/kubelet.service
    dest: /etc/systemd/system/kubelet.service
    owner: "{{ kubernetes.user }}"
    group: "{{ kubernetes.group }}"
  become: true
  notify: Restart kubelet

- name: Enabled kubelet.service
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: true
  become: true
