- name: install dependencies
  package:
    name: unzip
    state: present
  become: true

- name: get loki
  ansible.builtin.get_url:
    url: https://github.com/grafana/loki/releases/download/v{{ loki.version }}/loki-linux-amd64.zip
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}/loki-linux-amd64.zip"
  delegate_to: localhost
  run_once: true

- name: extract archive
  ansible.builtin.unarchive:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/loki-linux-amd64.zip"
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}"
  delegate_to: localhost
  run_once: true

- name: copy binary
  ansible.builtin.copy:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/loki-linux-amd64"
    dest: /usr/local/bin/loki
    owner: root
    group: root
    mode: 0755
  become: true

- name: create /etc/loki
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    owner: "{{ loki.user }}"
    group: "{{ loki.group }}"
    mode: 0755
  become: true

- name: copy config
  ansible.builtin.template:
    src: templates/config.yaml
    dest: /etc/loki/config.yaml
    owner: "{{ loki.user }}"
    group: "{{ loki.group }}"
    mode: 0644
  become: true

- name: copy service
  ansible.builtin.template:
    src: templates/loki.service
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart loki

- name: start service
  ansible.builtin.systemd:
    name: loki
    state: started
    enabled: true
    daemon_reload: true
  become: true
