---

- hosts: localhost
  tasks:
    - file:
        path: private
        mode: 0700
        state: directory

- hosts: all
  tasks:
    - apt:
        update_cache: yes

- hosts: tag_group_prometheus
  roles:
    - role: prometheus/node_exporter
    - role: prometheus/server
      vars:
        host_group:
          - tag_group_prometheus
          - tag_group_grafana

- hosts: tag_group_grafana
  roles:
    - role: prometheus/node_exporter
    - role: grafana