---

- hosts: all
  pre_tasks:
    - apt:
        update_cache: yes

- hosts: tag_group_prometheus
  roles:
    - role: prometheus/node_exporter
    - role: prometheus/server
      vars:
        host_group: tag_group_prometheus

- hosts: tag_group_grafana
  roles:
    - role: grafana