- name: create directory {{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}
  file:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}"
    state: directory
    mode: 0700

- name: generate private key
  openssl_privatekey:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.key"
    type: RSA
    size: 2048
    state: present
    mode: 0600

- name: generate csr
  openssl_csr:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.csr"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.key"
    common_name: "admin"
    organization_name: "system:masters"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    state: present
    mode: 0600

- name: generate crt
  openssl_certificate:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.crt"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.key"
    csr_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.csr"
    provider: ownca
    ownca_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    ownca_privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.key"
    mode: 0644

- name: create directory {{ ansible_env.PWD }}/.kube
  file:
    path: "{{ ansible_env.PWD }}/.kube"
    state: directory
    mode: 0700

- command: cat {{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.key
  register: key

- command: cat {{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/kube-admin.crt
  register: crt

- command: cat {{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt
  register: ca

- name: copy kubeconfig
  template:
    src: ../../common/templates/kubeconfig
    dest: "{{ ansible_env.PWD }}/.kube/config"
    mode: 0600
