- ansible.builtin.file:
    state: directory
    path: /sys/fs/cgroup/systemd
    owner: root
    group: root
    mode: 0755
  become: true

- mount:
    path: /sys/fs/cgroup/systemd
    src: cgroup
    fstype: cgroup
    opts: none,name=systemd
    state: mounted
    boot: true
    fstab: /etc/fstab
  become: true

- name: create download directory
  ansible.builtin.file:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}"
    state: directory
  delegate_to: localhost

- name: download package
  ansible.builtin.get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.6.2/containerd-1.6.2-linux-amd64.tar.gz
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}/containerd-1.6.2-linux-amd64.tar.gz"
    checksum: sha256:3d94f887de5f284b0d6ee61fa17ba413a7d60b4bb27d756a402b713a53685c6a
  delegate_to: localhost
  run_once: true

- name: unarchive package
  unarchive:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/containerd-1.6.2-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"

- name: copy binaries
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/bin/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
    remote_src: true
  with_items:
    - containerd
    - containerd-shim
    - containerd-shim-runc-v1
    - containerd-shim-runc-v2
    - containerd-stress
    - ctr
  become: true
  notify: restart containerd

- name: download runc
  ansible.builtin.get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{ containerd.version }}/runc.amd64
    dest: "{{ ansible_env.HOME }}/runc"
    checksum: "{{ containerd.checksum }}"

- name: copy binary
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/runc"
    dest: /usr/local/bin/runc
    owner: root
    group: root
    mode: 0755
    remote_src: true
  become: true

- name: copy service
  ansible.builtin.template:
    src: templates/containerd.service
    dest: /etc/systemd/system/containerd.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart containerd

- name: create /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: "{{ containerd.user }}"
    group: "{{ containerd.group }}"
    mode: 0644
  become: true

- name: copy config
  ansible.builtin.template:
    src: templates/config.toml
    dest: /etc/containerd/config.toml
    owner: "{{ containerd.user }}"
    group: "{{ containerd.group }}"
    mode: 0600
  become: true
  notify: restart containerd

- name: start service
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true
  become: true
